sudo: required
services: docker
language: python
python: 3.5

script:
  - git clone https://github.com/czka/archlinux-docker.git
  - git clone https://github.com/terencewestphal/get-archlinux-bootstrap.git
  - bash get-archlinux-bootstrap/get-archlinux-bootstrap.sh
  - cd archlinux-docker
  - 'sed -i "s/ln -s/ln -sf/" Dockerfile'
  - 'python3.5 tar_fix.py --input ../*.tar.gz --output bootstrap.tar.gz'
  - docker build --build-arg architecture=x86_64 -t archlinux .
  - '[[ $TRAVIS_PULL_REQUEST == false ]] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" || true'
  - '[[ $TRAVIS_PULL_REQUEST == false ]] && docker push archlinux:thecompiler/archlinux'

notifications:
  irc:
    channels:
      - "chat.freenode.net#qutebrowser-dev"
    on_success: always
    on_failure: always
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "%{compare_url} - %{build_url}"
