sudo: required
services: docker
language: python
python: 3.5

script:
  - docker build -t thecompiler/archlinux .
  - '[[ $TRAVIS_PULL_REQUEST == false ]] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" || true'
  - '[[ $TRAVIS_PULL_REQUEST == false ]] && docker push thecompiler/archlinux'

notifications:
  irc:
    channels:
      - "chat.freenode.net#qutebrowser-dev"
    on_success: always
    on_failure: always
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "%{compare_url} - %{build_url}"
